# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

In [2]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.9.1


### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [99]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?
import numpy as np
import time

arr = np.arange(1000000)
lista = list(range(1000000)) 
%time for _ in range(10): arr1 = [i ** 2 for i in arr]
%time for _ in range(10): lista1 = [i ** 2 for i in lista]

Wall time: 1.91 s
Wall time: 2.53 s


### Exercício 2

In [79]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0
array = np.array(np.random.randint(10, size=10))
array[5:8] = 0

### Exercício 3

In [103]:
# Crie um array de 3 dimensões e imprima a dimensão 1 
a = np.array(np.random.randint(10, size=3))
b = np.array(np.random.randint(5, size=3))
c = np.array(np.random.randint(11, size=3))
array = np.array([[a, b, c], [a, b, c] ])
print(array[0])

[[4 5 0]
 [1 4 3]
 [3 4 3]]


### Exercício 4

In [123]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
matrix = np.array([a, b, c])
print(matrix[:2, 1:]) # Terceira Coluna da matriz

[[5 0]
 [4 3]]


### Exercício 5

In [125]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [ ]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

### Exercício 7

In [126]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B
array = np.arange(10)
print(array)
np.save('array', array)

[0 1 2 3 4 5 6 7 8 9]


In [128]:
array = np.load('array.npy')
print(array)

[0 1 2 3 4 5 6 7 8 9]


### Exercício 8

In [133]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [135]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [149]:
import json
data = resp.json()
df = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])

In [150]:
df.head()

number                                              title  \
0   40928  CLN: preliminary refactor before `Styler.highl...   
1   40927   Fix 40420:  Interpret NaN in clip() as no bound.   
2   40926      [WIP] ENH: `Styler.highlight_quantile` method   
3   40925    DOC: inconsistency in doc argument types #40560   
4   40924            BUG: concat with DTI and all-None Index   

                                              labels state  
0                                                 []  open  
1                                                 []  open  
2                                                 []  open  
3                                                 []  open  
4  [{'id': 1218227310, 'node_id': 'MDU6TGFiZWwxMj...  open

number                                              title  \
0    20975  Slicing columns with mixed types <str>,<int> f...   
1    20974  BUG: Fix drop_duplicates failure when DataFram...   
2    20970            performance when "combining" categories   
3    20969        Getting a ... in my CSV when using to_csv()   
4    20968                         Sharey keyword for boxplot   
5    20967   Column can be extended beyond DataFrame's length   
6    20966             BUG: Fix wrong khash method definition   
7    20965  BUG: Fix combine_first converts other columns ...   
8    20964  BUG: Index with integer data and datetime64[ns...   
9    20962  df.rank() has different behavior for python2 a...   
10   20960  DOC: add reshaping visuals to the docs (Reshap...   
11   20958  Using apply on a grouper works only if done af...   
12   20956  ENH: Return DatetimeIndex or TimedeltaIndex bi...   
13   20955  Building documentation fails with `ImportError...   
14   20954  Correlation inconsistencies between Series and...   
15   20951  Addressing multiindex raises TypeError if indi...   
16   20948  Indexing DataFrame with DateOffset is nearly i...   
17   20947        Allow drop bins when using the cut function   
18   20945  Data is mismatched with labels after stack wit...   
19   20944                       Drop rows based on condition   
20   20943  pd.read_sql does not handle queries that retur...   
21   20940                       unclear error with  read_sas   
22   20937  BUG: Series(DTI/TDI) loses the frequency infor...   
23   20936  __new__() missing 1 required positional argume...   
24   20932  API: expose `axis` keyword in pandas.core.algo...   
25   20930  DOC: Index.get_loc Cannot Accept List-like Tol...   
26   20928             Added script to fetch wheels [ci skip]   
27   20927  read_sas OverflowError: int too big to convert...   
28   20926   BLD: Lint for invalid files in wheels / packages   
29   20925  Series.reset_index(level_name, drop=True) acce...   

                                               labels state  
0                                                  []  open  
1   [{'id': 76811, 'url': 'https://api.github.com/...  open  
2   [{'id': 78527356, 'url': 'https://api.github.c...  open  
3                                                  []  open  
4                                                  []  open  
5                                                  []  open  
6   [{'id': 76811, 'url': 'https://api.github.com/...  open  
7   [{'id': 76811, 'url': 'https://api.github.com/...  open  
8                                                  []  open  
9                                                  []  open  
10  [{'id': 134699, 'url': 'https://api.github.com...  open  
11  [{'id': 76811, 'url': 'https://api.github.com/...  open  
12  [{'id': 49597148, 'url': 'https://api.github.c...  open  
13                                                 []  open  
14                                                 []  open  
15                                                 []  open  
16                                                 []  open  
17  [{'id': 76812, 'url': 'https://api.github.com/...  open  
18                                                 []  open  
19                                                 []  open  
20                                                 []  open  
21                                                 []  open  
22                                                 []  open  
23                                                 []  open  
24  [{'id': 35818298, 'url': 'https://api.github.c...  open  
25                                                 []  open  
26  [{'id': 131473665, 'url': 'https://api.github....  open  
27                                                 []  open  
28  [{'id': 129350, 'url': 'https://api.github.com...  open  
29  [{'id': 42670965, 'url': 'https://api.github.c...  open

### Exercício 10

In [151]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas
import sqlite3

In [152]:
# Cria uma conexão com o banco de dados. 
# Se o banco de dados não existir, ele é criado neste momento.
con = sqlite3.connect('escola.db')

In [153]:
# Criando um cursor
cur = con.cursor()

In [160]:
# Cria uma instrução sql
sql_table = 'create table produtos' \
    '(id integer primary key,' \
    'titulo varchar(100),'\
    'categoria varchar(100),'\
    'preco float)'

cur.execute(sql_table)

In [161]:
sql_insert = 'insert into produtos values (?, ?, ?, ?)'

In [163]:
# Dados
dados = [(1, 'Lapis', 'Escolar', '5.30'), 
        (2, 'Caneta', 'Escolar', '9.60'),
        (3, 'Mochila', 'Escolar', '115.30'),
        (4, 'Borracha', 'Escolar', '1.30')
]

In [165]:
for dado in dados:
    cur.execute(sql_insert, dado)

In [166]:
# Grava a transação
con.commit()

In [169]:
sql_select = 'select * from produtos'

In [170]:
cur.execute(sql_select)
dados = cur.fetchall()

In [171]:
df = pd.DataFrame(dados, columns=['id', 'titulo', 'categoria', 'preco'])

In [180]:
df

id    titulo categoria  preco
0   1     Lapis   Escolar    5.3
1   2    Caneta   Escolar    9.6
2   3   Mochila   Escolar  115.3
3   4  Borracha   Escolar    1.3

In [179]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   id         4 non-null      int64  
 1   titulo     4 non-null      object 
 2   categoria  4 non-null      object 
 3   preco      4 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 256.0+ bytes


# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>